// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const PRISMA_GENERATE_PLACEHOLDER_URL =
  "postgresql://prisma:prisma@127.0.0.1:5432/prisma";

function hasRailwayRuntime(): boolean {
  return Boolean(
    process.env.RAILWAY_PROJECT_ID ||
      process.env.RAILWAY_SERVICE_ID ||
      process.env.RAILWAY_ENVIRONMENT_ID,
  );
}

function isPostgresUrl(value: string | undefined): value is string {
  if (!value) return false;

  return value.startsWith("postgresql://") || value.startsWith("postgres://");
}

function normalizeUrl(value: string | undefined): string | undefined {
  const trimmed = value?.trim();
  return trimmed ? trimmed : undefined;
}

function isPrismaGenerateCommand(): boolean {
  return process.argv.includes("generate");
}

function resolveDatabaseUrl(): string {
  const publicUrl = normalizeUrl(process.env.DATABASE_PUBLIC_URL);
  const internalUrl = normalizeUrl(process.env.DATABASE_URL);

  if (hasRailwayRuntime() && isPostgresUrl(internalUrl)) {
    return internalUrl;
  }

  if (isPostgresUrl(publicUrl)) {
    return publicUrl;
  }

  if (isPostgresUrl(internalUrl)) {
    return internalUrl;
  }

  if (hasRailwayRuntime() && internalUrl) {
    console.warn(
      "Ignoring invalid Railway DATABASE_URL because it is not a PostgreSQL URL.",
    );
  }

  if (isPrismaGenerateCommand()) {
    console.warn(
      "Using a placeholder PostgreSQL URL for prisma generate because no valid database URL is available yet.",
    );
    return PRISMA_GENERATE_PLACEHOLDER_URL;
  }

  if (publicUrl || internalUrl) {
    throw new Error(
      "Database URL is invalid. Set DATABASE_PUBLIC_URL or DATABASE_URL to a postgresql:// URL.",
    );
  }

  throw new Error(
    "Database URL is missing. Set DATABASE_PUBLIC_URL or DATABASE_URL.",
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: resolveDatabaseUrl(),
  },
});
