import fs from "node:fs";
import path from "node:path";

const SRC_DIR = path.resolve("src");
const OUTLINED_DIR = path.resolve(
  "node_modules/@material-symbols/svg-400/outlined",
);
const OUT_FILE = path.resolve("src/frontend/components/ui/iconPaths.ts");

const ALIASES = {
  emoji_events: "trophy",
  expand_less: "keyboard_arrow_up",
  expand_more: "keyboard_arrow_down",
  vibration: "mobile_vibrate",
  edgesensor_high: "flash_on",
  done: "check",
};

const FILLED_USED = new Set([
  "crown",
  "emoji_events",
  "progress_activity",
  "local_fire_department",
  "home",
  "sports_esports",
  "history",
  "person",
]);

function walk(dir, out = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full, out);
    else if (/\.(tsx|ts)$/.test(entry.name) && !entry.name.endsWith(".d.ts")) {
      out.push(full);
    }
  }
  return out;
}

const files = walk(SRC_DIR);
const names = new Set();

for (const file of files) {
  const source = fs.readFileSync(file, "utf8");
  const spanRe =
    /<span[^>]*material-symbols-outlined[^>]*>([\s\S]{0,120}?)<\/span>/g;
  let match;
  while ((match = spanRe.exec(source))) {
    const inner = match[1].replace(/<[^>]*>/g, "").trim();
    const literals = inner.match(/[a-z][a-z0-9_]*/g);
    if (!inner.startsWith("{") && /^[a-z][a-z0-9_]*$/.test(inner)) {
      names.add(inner);
    } else {
      for (const lit of inner.match(/["']([a-z][a-z0-9_]*)["']/g) ?? []) {
        names.add(lit.slice(1, -1));
      }
      for (const lit of inner.match(/[a-z][a-z0-9_]*/g) ?? []) {
        if (lit.includes("_")) names.add(lit);
      }
    }
  }

  const propRe = /\bicon["']?\s*[:=]\s*["']([a-z0-9_]+)["']/g;
  let propMatch;
  while ((propMatch = propRe.exec(source))) {
    names.add(propMatch[1]);
  }

  const iconExprRe = /\bicon=\{([\s\S]{0,160}?)\}/g;
  let exprMatch;
  while ((exprMatch = iconExprRe.exec(source))) {
    for (const lit of exprMatch[1].match(/["']([a-z][a-z0-9_]*)["']/g) ?? []) {
      names.add(lit.slice(1, -1));
    }
  }

  const iconCompRe = /<Icon\b([^>]*)>/g;
  let compMatch;
  while ((compMatch = iconCompRe.exec(source))) {
    const attrs = compMatch[1];
    const litName = attrs.match(/name="([a-z0-9_]+)"/);
    if (litName) {
      names.add(litName[1]);
    }
    const exprName = attrs.match(/name=\{([\s\S]{0,160}?)\}/);
    if (exprName) {
      for (const lit of exprName[1].match(/["']([a-z][a-z0-9_]*)["']/g) ?? []) {
        names.add(lit.slice(1, -1));
      }
      for (const lit of exprName[1].match(/[a-z][a-z0-9_]*/g) ?? []) {
        if (lit.includes("_") && !lit.startsWith("on")) names.add(lit);
      }
    }
  }
}

const missing = [];
const iconPaths = {};

for (const name of [...names].sort()) {
  const resolvedName = ALIASES[name] ?? name;
  const svgPath = path.join(OUTLINED_DIR, `${resolvedName}.svg`);
  if (!fs.existsSync(svgPath)) {
    missing.push(name);
    continue;
  }
  const extract = (file) => {
    const svg = fs.readFileSync(file, "utf8");
    return svg
      .replace(/^[\s\S]*?<svg[^>]*>/, "")
      .replace(/<\/svg>\s*$/, "")
      .trim();
  };
  iconPaths[name] = extract(svgPath);

  if (FILLED_USED.has(name)) {
    const fillPath = path.join(OUTLINED_DIR, `${resolvedName}-fill.svg`);
    if (fs.existsSync(fillPath)) {
      iconPaths[`${name}-fill`] = extract(fillPath);
    }
  }
}

if (missing.length > 0) {
  console.error("MISSING ICONS:", missing.join(", "));
  process.exit(1);
}

const lines = [
  "// AUTO-GENERATED by scripts/generate-icons.mjs from @material-symbols/svg-400.",
  "// Fill variants are emitted only for names in FILLED_USED. Do not edit manually. Regenerate with: node scripts/generate-icons.mjs",
  "export const ICON_PATHS = {",
  ...Object.entries(iconPaths).map(
    ([name, content]) => `  "${name}": ${JSON.stringify(content)},`,
  ),
  "} as const;",
  "",
  "export type IconName = keyof typeof ICON_PATHS;",
  "",
];

fs.writeFileSync(OUT_FILE, lines.join("\n"));
console.log(`Generated ${Object.keys(iconPaths).length} icons -> ${OUT_FILE}`);
